spring:
  application:
    name: email-notif-service
  mail:
    host: smtp.gmail.com
    port: 465
    username: abdelrhmanadelameen500@gmail.com
    password: kiwahwbwdrjxtmuk
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
logging:
  level:
    org.springframework.mail: DEBUG

server:
  port: 9096


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



