spring:
  application:
    name: product-service
    bucket:
      name: abdelrahmanecommerce
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product
    username: abdelrahman
    password: abdelrahman
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082


kafka:
  server:
    url: localhost:9092


cloud:
  aws:
    credentials:
      access-key: AKIA2AUOPCC2UZ3OYZ22
      secret-key: 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
    region:
      static : eu-north-1
    stack:
      auto : false

