spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter

        - id: product-service-websocket
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/websocket/**
          filters:
            - AuthenticationFilter

        - id: product-nosql-service
          uri: lb:http://PRODUCT-NOSQL-SERVICE
          predicates:
            - Path=/noSqlProducts/**
          filters:
            - AuthenticationFilter

        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
          filters:
            - AuthenticationFilter

        - id: authentication-service
          uri: lb:http://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: email-notif-service
          uri: lb:http://EMAIL-NOTIF-SERVICE
          predicates:
            - Path=/email/**

        - id: inventory-service
          uri: lb:http://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

  application:
    name: getway-service


server:
  port: 8222


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


