spring:
  application:
    name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order
      username: abdelrahman
      password: abdelrahman
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8085









