spring:
  application:
    name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order
      username: abdelrahman
      password: abdelrahman
      authentication-database: admin
  cache:
    type: redis
    host: localhost
    port: 6379
    password: abdelrahman
    time-to-live: 60000



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8085






